# generated by chapt gpt 4.0
# created for copying common dependency files such as camera calibration data to archival packge folders
# to do modify to allow copying whole folders

import os
import shutil

def copy_file_to_subfolders(src_file, target_dir, subfolder_name):
    """
    Copy the specified file into a new folder within each subdirectory of the target directory.
    
    Args:
        src_file (str): Path to the source file.
        target_dir (str): Path to the target directory where the subfolders reside.
        subfolder_name (str): Name of the subfolder to create within each subdirectory.
    """

    # Iterate over each item in the target directory
    for subdir in os.listdir(target_dir):
        subdir_path = os.path.join(target_dir, subdir)
        
        if os.path.isdir(subdir_path):  # Ensure it's a directory
            # Define the new subfolder path using the specified name
            calibration_folder_path = os.path.join(subdir_path, subfolder_name)
            os.makedirs(calibration_folder_path, exist_ok=True)  # Create the folder if it doesn't exist
            
            # Define the destination file path within the calibration folder
            dest_file_path = os.path.join(calibration_folder_path, os.path.basename(src_file))
            
            # Copy the source file to the destination
            shutil.copy(src_file, dest_file_path)
            print(f"Copied {src_file} to {dest_file_path}")

# Usage example
src_file_path = '/path/to/your/source/file.txt'  # Change this to the file you want to copy
target_directory = '/path/to/the/target/directory'  # Change this to the target directory
subfolder_name = 'camera calibration'  # Specify the subfolder name

copy_file_to_subfolders(src_file_path, target_directory, subfolder_name)
